# Generated by Django 4.1 on 2024-04-06 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "city_id",
                    models.PositiveSmallIntegerField(primary_key=True, serialize=False),
                ),
                ("city_name", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "place_id",
                    models.PositiveIntegerField(primary_key=True, serialize=False),
                ),
                ("place_name", models.CharField(max_length=100)),
                ("place_address", models.CharField(max_length=100)),
                ("place_latitude", models.DecimalField(decimal_places=6, max_digits=8)),
                (
                    "place_longitude",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                ("place_eco", models.BooleanField(default=False)),
                (
                    "place_city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PlanT_Backend.city",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "plan_id",
                    models.PositiveIntegerField(primary_key=True, serialize=False),
                ),
                ("plan_date", models.DateField()),
                (
                    "plan_city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PlanT_Backend.city",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "tag_id",
                    models.PositiveSmallIntegerField(primary_key=True, serialize=False),
                ),
                ("tag_name", models.CharField(max_length=20)),
                ("tag_time", models.PositiveSmallIntegerField()),
                ("tag_co2", models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "user_id",
                    models.CharField(max_length=15, primary_key=True, serialize=False),
                ),
                ("user_pw", models.CharField(max_length=20)),
                ("user_name", models.CharField(max_length=45, null=True, unique=True)),
                ("user_email", models.EmailField(max_length=45, unique=True)),
                ("user_point", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "trip_id",
                    models.PositiveIntegerField(primary_key=True, serialize=False),
                ),
                ("trip_start", models.DateField()),
                ("trip_end", models.DateField()),
                (
                    "trip_state",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "예정"), (2, "진행중"), (3, "완료")]
                    ),
                ),
                (
                    "trip_ecolevel",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Level 0"),
                            (1, "Level 1"),
                            (2, "Level 2"),
                            (3, "Level 3"),
                            (4, "Level 4"),
                            (5, "Level 5"),
                        ]
                    ),
                ),
                ("trip_posstime", models.PositiveSmallIntegerField()),
                (
                    "trip_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PlanT_Backend.users",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "route_id",
                    models.PositiveIntegerField(primary_key=True, serialize=False),
                ),
                (
                    "route_type",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "친환경 경로"), (2, "최단 경로"), (3, "지정 경로")]
                    ),
                ),
                (
                    "route_transport",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "도보"), (2, "자전거"), (3, "대중교통"), (4, "자동차")]
                    ),
                ),
                ("route_starttime", models.DateTimeField()),
                ("route_endtime", models.DateTimeField()),
                ("route_time", models.PositiveSmallIntegerField()),
                ("route_co2", models.PositiveSmallIntegerField()),
                ("route_detail", models.JSONField(blank=True, default=None, null=True)),
                (
                    "route_end",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_end_place",
                        to="PlanT_Backend.place",
                    ),
                ),
                (
                    "route_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PlanT_Backend.plan",
                    ),
                ),
                (
                    "route_start",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_start_place",
                        to="PlanT_Backend.place",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="plan",
            name="plan_trip",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="PlanT_Backend.trip"
            ),
        ),
        migrations.AddField(
            model_name="place",
            name="place_tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="PlanT_Backend.tag"
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="city_tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="PlanT_Backend.tag"
            ),
        ),
    ]
