# Generated by Django 4.1 on 2024-04-14 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PlanT_Backend", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="plan_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="route",
            name="route_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="trip",
            name="trip_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
